### ISSUE TITLE
请问数据集文件结构是什么？

### ISSUE THREAD

**Issue by kekukin** [lab-midas/GMARAFT#1]

**Comment by Aya-Gh** [comment]
The dataset is organized as follows:

1. Fully Sampled Data:

The fully sampled data is stored in HDF5 (.h5) format under the path: **dataroot/h5/subjectname.h5.**
Within each HDF5 file, the fully sampled images can be accessed under the group/key **dImgC**.

2. Accelerated Data:

The accelerated (undersampled) data is saved as NumPy arrays (.npy) and organized under the path:
**dataroot/sampling/R{R}/{subjectname}_img.npy**.

Here:
- dataroot is the base directory for the dataset.
- sampling specifies the sampling type (e.g., Cartesian, radial, etc.).
- R{R} indicates the acceleration factor (e.g., R4 for 4x acceleration).
- {subjectname} is the specific filename for the dataset.

Let me know if further clarification is needed!
